# Generated by Django 2.0.6 on 2019-06-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('salary', models.FloatField()),
                ('is_married', models.BooleanField()),
            ],
            options={
                'db_table': 'emps',
            },
        ),
    ]
