# Generated by Django 2.0.6 on 2019-08-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'huawei_advertisement',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.TextField(null=True)),
                ('goods_id', models.BigIntegerField(verbose_name='商品id')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名字')),
                ('goods_price', models.IntegerField(verbose_name='商品价格')),
                ('goods_black_discount', models.CharField(max_length=100, null=True)),
                ('goods_red_discount', models.CharField(max_length=100, null=True)),
                ('goods_promotion', models.CharField(max_length=100, null=True)),
                ('goods_color', models.CharField(max_length=100, null=True)),
                ('goods_edition', models.CharField(max_length=50, null=True)),
                ('goods_set_meal', models.CharField(max_length=50, null=True)),
                ('goods_num', models.IntegerField(default=1)),
                ('goods_guarantee', models.CharField(max_length=100, null=True)),
                ('goods_service', models.CharField(max_length=100, null=True)),
                ('goods_info_img_src', models.TextField(null=True)),
                ('g_evaluate', models.IntegerField()),
                ('g_good', models.IntegerField()),
                ('g_img', models.CharField(max_length=256, null=True)),
                ('g_name', models.CharField(max_length=20, null=True)),
                ('g_good_info', models.TextField(null=True)),
                ('main_param', models.TextField()),
                ('param_info', models.TextField(null=True)),
                ('param_baozhuang', models.TextField(null=True)),
            ],
            options={
                'verbose_name': '商品模型',
                'verbose_name_plural': '商品模型',
                'db_table': 'huawei_goods',
            },
        ),
        migrations.CreateModel(
            name='HomeFurnishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_homefurnishing',
            },
        ),
        migrations.CreateModel(
            name='NotebookComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_notebookcomputer',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_phone',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField()),
                ('typename', models.CharField(max_length=50)),
                ('childtypenames', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'huawei_producttype',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_recommend',
            },
        ),
        migrations.CreateModel(
            name='SellWell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_sellwell',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'show',
            },
        ),
        migrations.CreateModel(
            name='ShowDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_src', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'show_down',
            },
        ),
        migrations.CreateModel(
            name='ShowLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'show_left',
            },
        ),
        migrations.CreateModel(
            name='TablePC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_tablePC',
            },
        ),
        migrations.CreateModel(
            name='UserEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('user_img', models.CharField(max_length=256)),
                ('user_name', models.CharField(max_length=20)),
                ('user_text', models.TextField()),
                ('user_pic', models.TextField()),
            ],
            options={
                'db_table': 'huawei_userevaluate',
            },
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
                ('good_other_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'huawei_wear',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'huawei_wheel',
            },
        ),
    ]
