# Generated by Django 2.0.6 on 2019-07-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_goods_num', models.IntegerField()),
                ('o_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'db_table': 'axf_orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_price', models.FloatField()),
                ('o_time', models.DateTimeField(auto_now=True)),
                ('o_state', models.IntegerField(default=1)),
                ('o_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.AXFUser')),
            ],
            options={
                'db_table': 'axf_orders',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='o_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders'),
        ),
    ]
