# Generated by Django 2.0.6 on 2019-08-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'xiaomi_advertisement',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.TextField(null=True)),
                ('goods_id', models.BigIntegerField(verbose_name='商品id')),
                ('goods_name', models.CharField(max_length=50, verbose_name='商品名字')),
                ('goods_price', models.IntegerField(verbose_name='商品价格')),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_img_info', models.TextField(null=True)),
                ('goods_yellow_discount', models.CharField(max_length=100, null=True)),
                ('goods_black_discount', models.CharField(max_length=100, null=True)),
                ('goods_info_img_src', models.TextField(null=True)),
            ],
            options={
                'verbose_name': '商品模型',
                'verbose_name_plural': '商品模型',
                'db_table': 'xiaomi_goods',
            },
        ),
        migrations.CreateModel(
            name='HomeFurnishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'xiaomi_home',
            },
        ),
        migrations.CreateModel(
            name='NewGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
                ('goods_name', models.CharField(max_length=50, null=True)),
                ('goods_info', models.CharField(max_length=50, null=True)),
                ('goods_price', models.IntegerField(null=True)),
                ('goods_del_price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'xiaomi_newgoods',
            },
        ),
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
                ('goods_name', models.CharField(max_length=50, null=True)),
                ('goods_info', models.CharField(max_length=50, null=True)),
                ('goods_price', models.IntegerField(null=True)),
                ('goods_del_price', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'xiaomi_newmodel',
            },
        ),
        migrations.CreateModel(
            name='NotebookComputer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'xiaomi_notebookcomputer',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'xiaomi_phone',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeid', models.IntegerField()),
                ('typename', models.CharField(max_length=50)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField()),
            ],
            options={
                'db_table': 'xiaomi_producttype',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src_info', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'xiaomi_show',
            },
        ),
        migrations.CreateModel(
            name='ShowDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('child_id', models.IntegerField()),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=20)),
                ('goods_src', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'show_down',
            },
        ),
        migrations.CreateModel(
            name='ShowLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'show_left',
            },
        ),
        migrations.CreateModel(
            name='UserEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('user_star', models.IntegerField()),
                ('user_time', models.DateTimeField()),
                ('user_text', models.TextField()),
                ('user_pic', models.TextField()),
                ('user_good', models.IntegerField()),
                ('user_official', models.TextField()),
                ('user_official_good', models.IntegerField()),
                ('user_name', models.ForeignKey(on_delete=True, to='user.XiaomiUser')),
            ],
            options={
                'db_table': 'xiaomi_userevaluate',
            },
        ),
        migrations.CreateModel(
            name='WatchTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_id', models.BigIntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('img_src_info', models.CharField(max_length=256, null=True)),
                ('goods_price', models.IntegerField()),
                ('goods_del_price', models.IntegerField(null=True)),
                ('goods_free', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'xiaomi_watchTV',
            },
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'xiaomi_wheel',
            },
        ),
    ]
