"""
Django settings for Dianshang project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xx#44710ky-sriwe03l-onvhg(p223d0)5p8!^x+481h)%frgr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user',
    "carts",
    "goods",
    'orders',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'middleware.mymiddleware.FirstMiddleware',

]

ROOT_URLCONF = 'xiaomi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xiaomi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xiaomi',
        'HOST':'localhost',
        'PORT':3306,
        'USER':'root',
        'PASSWORD':'123456',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.163.com'    # 负责发送邮件的服务器地址
EMAIL_PORT = 25   # SMTP服务器非SSL协议端口
EMAIL_HOST_USER = 'bajing337191@163.com'  # 账号
EMAIL_HOST_PASSWORD = 'ds1902'    # 邮箱客户端授权码

REST_FRAMEWORK = {
    # 重构renderer
    'DEFAULT_RENDERER_CLASSES': (
        'util.renderer.HWRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
         'django_filters.rest_framework.DjangoFilterBackend',
   ),
}

#跨域允许的请求方式
CORS_ALLOW_METHODS = (
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS'
)

#允许跨域的请求头
CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
)

CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True

#缓存配置
CACHES = {
     'default': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
          'PASSWORD':'',
        }
    }
}


alipay_public_key_string = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAveSf2bIIhk1qqnXYTgFQEbRWragD8pZ3SNSnuB
Ri1Tew4MB3FY0Ky1iLQzNMP3KWx466beWe6ujdxJKfYv8CQk+xhKv/AOT5Jf/UlG94KQBsN+NNJEBGkYXQnvu2fnPO+Cvxmpsp8KNdjnOOzViP
vmgRUI4Pcu7rWRLiDhj8Fq2j7cTBdD36S0Xpwh9jwPB7ctHO6vOjSS9XPPyTTxxtDRqZ+sFz0LbPN7XTJMazwJ9STPc88bEi26VivCnuNdp5Mq
wjY52maolqf9V1w9aUk3AoBckvQNs1qGB6/opt6+eDWr6nyEFjncm0YgE8ANM2Fr0h6CL+lEIkoRsAXyinJQIDAQAB
-----END PUBLIC KEY-----"""

app_private_key_string = """-----BEGIN RSA PRIVATE KEY-----
MIIEpgIBAAKCAQEAveSf2bIIhk1qqnXYTgFQEbRWragD8pZ3SNSnuBRi1Tew4MB3FY0Ky1iLQzNMP3KWx466
beWe6ujdxJKfYv8CQk+xhKv/AOT5Jf/UlG94KQBsN+NNJEBGkYXQnvu2fnPO+Cvxmpsp8KNdjnOOzViPvmgRUI4Pcu7rWRLiDhj8Fq2j7cTBdD
36S0Xpwh9jwPB7ctHO6vOjSS9XPPyTTxxtDRqZ+sFz0LbPN7XTJMazwJ9STPc88bEi26VivCnuNdp5MqwjY52maolqf9V1w9aUk3AoBckvQNs1
qGB6/opt6+eDWr6nyEFjncm0YgE8ANM2Fr0h6CL+lEIkoRsAXyinJQIDAQABAoIBAQCHW/0GNP4WngC22aICmLT2qdJPn0CRH+iPpeaYNQ/uZP
BUhV1do1hacxdyI5Lqd0g7n+YMiG2rjarngIzVCGoX0q77n476mD1xdNeXp43DzGVXwVMv0BF9kiGP8mW35d1W0hw61PgkbI84B+93OPXeCFiv
T1R73QsuR2OUIQMxNgH3Ln17fLsJhvtIPqw8iW0Uo/AhEAin/M48bijsvDrqXCjCler9whWUphPUOtE7kiVsVX7osS8Nn6nHqLqBaBnZt4X7xn
0uf4qCG8waPpwMO+E/oyshUbc+WY9LraMsTCQjCSPiX7FdCxrEseW/K2l5RWtICrQ7iv8lZhIeiAbRAoGBAPAUzCH6WZwny7fSYdjjnvfwJwue
FEicuis5bT/DUHZKpDAQyLYPlxxxPFEUWmqYZf6MdknoWDFTu/nAgpUBilGv9MZ9xgiMxXh8AOO6ixGpCJ3tjmFisvcSCAdCasw0Y1R+9iikth
d2d2pqegoCaZVlZUiZLNnDY3//zrJH1GZ7AoGBAMp762x1THjvGaJpHvNs/iqMjBfRLcX+COX+44jLiGjLJdd/UVT65fGPag1URZbqQqjUocRs
W69RbSwueMHb8MkuJICsse51pJg+rAz+mu+OUfv4VZMqCdxXyEb9cGl7dc0lJDFOAT+tYTICgZemxXe4msnedXOrrRydwyf9zYbfAoGBAKT0VT
F/VrSRL0q09V/VPXNzgRBdY+hkLxHl2id2ZkFwlZEk5xMYcSYss1muF1WoMmQMVHYBex8hPkWivNXuggAQWqlK35ceScu3v9C4ajcPIgmIoExP
SVGzBOsf+ksmL51twmo4iZhjYDcww3s/HxZz3XxdKlDRC/t1Yqph6hEjAoGBAJWmCFTcTGyEqflyn8FhKGfiABgKLT5LheAWBawwYNyyZ4FhQ4
b+97sUN1kqk1P6RtHodLZrL0ffckRZBD6igs7tH2VKPSb0I3WxvA7OjUvHb6g93WEqjKcg6ZAt90q+SE4ZySn3cMzTIyaG26htRTw6X4wascuP
ch3YK0f/OEsZAoGBAK8uJgAHTzkinzn+iEYjwrYF8PZ5DKsqqAU8KROt5fvkByRfw5DTmFcefYnabkNr9z/0IAF1k8jTkoyUwwCJUxvv5SJ3JR
eT/ewZ2eD8IzJ11opr0LPLPXUaj6jQubMvY0jmE3OPolUzROSLwGLeGPkpdoob4jQTckcnL8R4rOKQ
-----END RSA PRIVATE KEY-----"""